// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tool_approvals.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countConsecutiveDenials = `-- name: CountConsecutiveDenials :one
SELECT COUNT(*) FROM (
  SELECT decision FROM tool_approvals
  WHERE flow_id = $1
  ORDER BY requested_at DESC
) sub
WHERE sub.decision = 'denied'
`

func (q *Queries) CountConsecutiveDenials(ctx context.Context, flowID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConsecutiveDenials, flowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createToolApproval = `-- name: CreateToolApproval :one
INSERT INTO tool_approvals (
  flow_id, task_id, tool_call_id, tool_name, args, risk_class, decision, requested_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, 'pending', NOW()
)
RETURNING id, flow_id, task_id, tool_call_id, tool_name, args, risk_class, decision, edited_args, reason, decided_by, requested_at, decided_at, created_at
`

type CreateToolApprovalParams struct {
	FlowID     int64           `json:"flow_id"`
	TaskID     sql.NullInt64   `json:"task_id"`
	ToolCallID string          `json:"tool_call_id"`
	ToolName   string          `json:"tool_name"`
	Args       json.RawMessage `json:"args"`
	RiskClass  RiskClass       `json:"risk_class"`
}

func (q *Queries) CreateToolApproval(ctx context.Context, arg CreateToolApprovalParams) (ToolApproval, error) {
	row := q.db.QueryRowContext(ctx, createToolApproval,
		arg.FlowID,
		arg.TaskID,
		arg.ToolCallID,
		arg.ToolName,
		arg.Args,
		arg.RiskClass,
	)
	var i ToolApproval
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.TaskID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.RiskClass,
		&i.Decision,
		&i.EditedArgs,
		&i.Reason,
		&i.DecidedBy,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAllPendingToolApprovals = `-- name: GetAllPendingToolApprovals :many
SELECT id, flow_id, task_id, tool_call_id, tool_name, args, risk_class, decision, edited_args, reason, decided_by, requested_at, decided_at, created_at FROM tool_approvals
WHERE decision = 'pending'
ORDER BY requested_at ASC
`

func (q *Queries) GetAllPendingToolApprovals(ctx context.Context) ([]ToolApproval, error) {
	rows, err := q.db.QueryContext(ctx, getAllPendingToolApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApproval
	for rows.Next() {
		var i ToolApproval
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.TaskID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.RiskClass,
			&i.Decision,
			&i.EditedArgs,
			&i.Reason,
			&i.DecidedBy,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingToolApprovals = `-- name: GetPendingToolApprovals :many
SELECT id, flow_id, task_id, tool_call_id, tool_name, args, risk_class, decision, edited_args, reason, decided_by, requested_at, decided_at, created_at FROM tool_approvals
WHERE flow_id = $1 AND decision = 'pending'
ORDER BY requested_at ASC
`

func (q *Queries) GetPendingToolApprovals(ctx context.Context, flowID int64) ([]ToolApproval, error) {
	rows, err := q.db.QueryContext(ctx, getPendingToolApprovals, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApproval
	for rows.Next() {
		var i ToolApproval
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.TaskID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.RiskClass,
			&i.Decision,
			&i.EditedArgs,
			&i.Reason,
			&i.DecidedBy,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolApproval = `-- name: GetToolApproval :one
SELECT id, flow_id, task_id, tool_call_id, tool_name, args, risk_class, decision, edited_args, reason, decided_by, requested_at, decided_at, created_at FROM tool_approvals
WHERE id = $1
`

func (q *Queries) GetToolApproval(ctx context.Context, id int64) (ToolApproval, error) {
	row := q.db.QueryRowContext(ctx, getToolApproval, id)
	var i ToolApproval
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.TaskID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.RiskClass,
		&i.Decision,
		&i.EditedArgs,
		&i.Reason,
		&i.DecidedBy,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getToolApprovalsByFlow = `-- name: GetToolApprovalsByFlow :many
SELECT id, flow_id, task_id, tool_call_id, tool_name, args, risk_class, decision, edited_args, reason, decided_by, requested_at, decided_at, created_at FROM tool_approvals
WHERE flow_id = $1
ORDER BY requested_at DESC
`

func (q *Queries) GetToolApprovalsByFlow(ctx context.Context, flowID int64) ([]ToolApproval, error) {
	rows, err := q.db.QueryContext(ctx, getToolApprovalsByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApproval
	for rows.Next() {
		var i ToolApproval
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.TaskID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.RiskClass,
			&i.Decision,
			&i.EditedArgs,
			&i.Reason,
			&i.DecidedBy,
			&i.RequestedAt,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateToolApprovalDecision = `-- name: UpdateToolApprovalDecision :one
UPDATE tool_approvals
SET decision = $1, edited_args = $2, reason = $3, decided_by = $4, decided_at = NOW()
WHERE id = $5 AND decision = 'pending'
RETURNING id, flow_id, task_id, tool_call_id, tool_name, args, risk_class, decision, edited_args, reason, decided_by, requested_at, decided_at, created_at
`

type UpdateToolApprovalDecisionParams struct {
	Decision   ToolApprovalDecision `json:"decision"`
	EditedArgs NullRawMessage       `json:"edited_args"`
	Reason     sql.NullString       `json:"reason"`
	DecidedBy  sql.NullInt64        `json:"decided_by"`
	ID         int64                `json:"id"`
}

func (q *Queries) UpdateToolApprovalDecision(ctx context.Context, arg UpdateToolApprovalDecisionParams) (ToolApproval, error) {
	row := q.db.QueryRowContext(ctx, updateToolApprovalDecision,
		arg.Decision,
		arg.EditedArgs,
		arg.Reason,
		arg.DecidedBy,
		arg.ID,
	)
	var i ToolApproval
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.TaskID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.RiskClass,
		&i.Decision,
		&i.EditedArgs,
		&i.Reason,
		&i.DecidedBy,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}
