// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tool_approvals.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const cancelFlowPendingToolApprovals = `-- name: CancelFlowPendingToolApprovals :many
UPDATE tool_approvals
SET
  decision = 'cancelled',
  reason = $1,
  decided_at = CURRENT_TIMESTAMP
WHERE flow_id = $2 AND decision = 'pending'
RETURNING id, flow_id, task_id, subtask_id, assistant_id, agent, tool_call_id, tool_name, args, risk_class, risk_reason, decision, edited_args, reason, decided_by, created_at, decided_at
`

type CancelFlowPendingToolApprovalsParams struct {
	Reason string `json:"reason"`
	FlowID int64  `json:"flow_id"`
}

func (q *Queries) CancelFlowPendingToolApprovals(ctx context.Context, arg CancelFlowPendingToolApprovalsParams) ([]ToolApproval, error) {
	rows, err := q.db.QueryContext(ctx, cancelFlowPendingToolApprovals, arg.Reason, arg.FlowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApproval
	for rows.Next() {
		var i ToolApproval
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.TaskID,
			&i.SubtaskID,
			&i.AssistantID,
			&i.Agent,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.RiskClass,
			&i.RiskReason,
			&i.Decision,
			&i.EditedArgs,
			&i.Reason,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelPendingToolApprovals = `-- name: CancelPendingToolApprovals :many
UPDATE tool_approvals
SET
  decision = 'cancelled',
  reason = $1,
  decided_at = CURRENT_TIMESTAMP
WHERE decision = 'pending'
RETURNING id, flow_id, task_id, subtask_id, assistant_id, agent, tool_call_id, tool_name, args, risk_class, risk_reason, decision, edited_args, reason, decided_by, created_at, decided_at
`

func (q *Queries) CancelPendingToolApprovals(ctx context.Context, reason string) ([]ToolApproval, error) {
	rows, err := q.db.QueryContext(ctx, cancelPendingToolApprovals, reason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApproval
	for rows.Next() {
		var i ToolApproval
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.TaskID,
			&i.SubtaskID,
			&i.AssistantID,
			&i.Agent,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.RiskClass,
			&i.RiskReason,
			&i.Decision,
			&i.EditedArgs,
			&i.Reason,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFlowTrailingDenials = `-- name: CountFlowTrailingDenials :one
SELECT
  COUNT(*)::BIGINT
FROM tool_approvals ta
WHERE ta.flow_id = $1
  AND ta.decision = 'denied'
  AND ta.id > COALESCE((
    SELECT MAX(granted.id)
    FROM tool_approvals granted
    WHERE granted.flow_id = $1 AND granted.decision IN ('approved', 'edited')
  ), 0)
`

// A denial streak is broken by an approval or an edit, not by a timeout or a cancellation.
func (q *Queries) CountFlowTrailingDenials(ctx context.Context, flowID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFlowTrailingDenials, flowID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createToolApproval = `-- name: CreateToolApproval :one
INSERT INTO tool_approvals (
  flow_id,
  task_id,
  subtask_id,
  assistant_id,
  agent,
  tool_call_id,
  tool_name,
  args,
  risk_class,
  risk_reason
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, flow_id, task_id, subtask_id, assistant_id, agent, tool_call_id, tool_name, args, risk_class, risk_reason, decision, edited_args, reason, decided_by, created_at, decided_at
`

type CreateToolApprovalParams struct {
	FlowID      int64           `json:"flow_id"`
	TaskID      sql.NullInt64   `json:"task_id"`
	SubtaskID   sql.NullInt64   `json:"subtask_id"`
	AssistantID sql.NullInt64   `json:"assistant_id"`
	Agent       MsgchainType    `json:"agent"`
	ToolCallID  string          `json:"tool_call_id"`
	ToolName    string          `json:"tool_name"`
	Args        json.RawMessage `json:"args"`
	RiskClass   ToolRiskClass   `json:"risk_class"`
	RiskReason  string          `json:"risk_reason"`
}

func (q *Queries) CreateToolApproval(ctx context.Context, arg CreateToolApprovalParams) (ToolApproval, error) {
	row := q.db.QueryRowContext(ctx, createToolApproval,
		arg.FlowID,
		arg.TaskID,
		arg.SubtaskID,
		arg.AssistantID,
		arg.Agent,
		arg.ToolCallID,
		arg.ToolName,
		arg.Args,
		arg.RiskClass,
		arg.RiskReason,
	)
	var i ToolApproval
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.TaskID,
		&i.SubtaskID,
		&i.AssistantID,
		&i.Agent,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.RiskClass,
		&i.RiskReason,
		&i.Decision,
		&i.EditedArgs,
		&i.Reason,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const decideToolApproval = `-- name: DecideToolApproval :one
UPDATE tool_approvals
SET
  decision = $1,
  edited_args = $2,
  reason = $3,
  decided_by = $4,
  decided_at = CURRENT_TIMESTAMP
WHERE id = $5 AND decision = 'pending'
RETURNING id, flow_id, task_id, subtask_id, assistant_id, agent, tool_call_id, tool_name, args, risk_class, risk_reason, decision, edited_args, reason, decided_by, created_at, decided_at
`

type DecideToolApprovalParams struct {
	Decision   ToolApprovalDecision  `json:"decision"`
	EditedArgs pqtype.NullRawMessage `json:"edited_args"`
	Reason     string                `json:"reason"`
	DecidedBy  sql.NullInt64         `json:"decided_by"`
	ID         int64                 `json:"id"`
}

func (q *Queries) DecideToolApproval(ctx context.Context, arg DecideToolApprovalParams) (ToolApproval, error) {
	row := q.db.QueryRowContext(ctx, decideToolApproval,
		arg.Decision,
		arg.EditedArgs,
		arg.Reason,
		arg.DecidedBy,
		arg.ID,
	)
	var i ToolApproval
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.TaskID,
		&i.SubtaskID,
		&i.AssistantID,
		&i.Agent,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.RiskClass,
		&i.RiskReason,
		&i.Decision,
		&i.EditedArgs,
		&i.Reason,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getAllPendingToolApprovals = `-- name: GetAllPendingToolApprovals :many
SELECT
  ta.id, ta.flow_id, ta.task_id, ta.subtask_id, ta.assistant_id, ta.agent, ta.tool_call_id, ta.tool_name, ta.args, ta.risk_class, ta.risk_reason, ta.decision, ta.edited_args, ta.reason, ta.decided_by, ta.created_at, ta.decided_at
FROM tool_approvals ta
WHERE ta.decision = 'pending'
ORDER BY ta.id ASC
`

func (q *Queries) GetAllPendingToolApprovals(ctx context.Context) ([]ToolApproval, error) {
	rows, err := q.db.QueryContext(ctx, getAllPendingToolApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApproval
	for rows.Next() {
		var i ToolApproval
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.TaskID,
			&i.SubtaskID,
			&i.AssistantID,
			&i.Agent,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.RiskClass,
			&i.RiskReason,
			&i.Decision,
			&i.EditedArgs,
			&i.Reason,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowPendingToolApprovals = `-- name: GetFlowPendingToolApprovals :many
SELECT
  ta.id, ta.flow_id, ta.task_id, ta.subtask_id, ta.assistant_id, ta.agent, ta.tool_call_id, ta.tool_name, ta.args, ta.risk_class, ta.risk_reason, ta.decision, ta.edited_args, ta.reason, ta.decided_by, ta.created_at, ta.decided_at
FROM tool_approvals ta
WHERE ta.flow_id = $1 AND ta.decision = 'pending'
ORDER BY ta.id ASC
`

func (q *Queries) GetFlowPendingToolApprovals(ctx context.Context, flowID int64) ([]ToolApproval, error) {
	rows, err := q.db.QueryContext(ctx, getFlowPendingToolApprovals, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApproval
	for rows.Next() {
		var i ToolApproval
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.TaskID,
			&i.SubtaskID,
			&i.AssistantID,
			&i.Agent,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.RiskClass,
			&i.RiskReason,
			&i.Decision,
			&i.EditedArgs,
			&i.Reason,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowToolApprovals = `-- name: GetFlowToolApprovals :many
SELECT
  ta.id, ta.flow_id, ta.task_id, ta.subtask_id, ta.assistant_id, ta.agent, ta.tool_call_id, ta.tool_name, ta.args, ta.risk_class, ta.risk_reason, ta.decision, ta.edited_args, ta.reason, ta.decided_by, ta.created_at, ta.decided_at
FROM tool_approvals ta
WHERE ta.flow_id = $1
ORDER BY ta.created_at DESC, ta.id DESC
`

func (q *Queries) GetFlowToolApprovals(ctx context.Context, flowID int64) ([]ToolApproval, error) {
	rows, err := q.db.QueryContext(ctx, getFlowToolApprovals, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApproval
	for rows.Next() {
		var i ToolApproval
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.TaskID,
			&i.SubtaskID,
			&i.AssistantID,
			&i.Agent,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.RiskClass,
			&i.RiskReason,
			&i.Decision,
			&i.EditedArgs,
			&i.Reason,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToolApproval = `-- name: GetToolApproval :one
SELECT
  ta.id, ta.flow_id, ta.task_id, ta.subtask_id, ta.assistant_id, ta.agent, ta.tool_call_id, ta.tool_name, ta.args, ta.risk_class, ta.risk_reason, ta.decision, ta.edited_args, ta.reason, ta.decided_by, ta.created_at, ta.decided_at
FROM tool_approvals ta
WHERE ta.id = $1
`

func (q *Queries) GetToolApproval(ctx context.Context, id int64) (ToolApproval, error) {
	row := q.db.QueryRowContext(ctx, getToolApproval, id)
	var i ToolApproval
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.TaskID,
		&i.SubtaskID,
		&i.AssistantID,
		&i.Agent,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.RiskClass,
		&i.RiskReason,
		&i.Decision,
		&i.EditedArgs,
		&i.Reason,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}
